---

- name: Create LXD Container Nginx
  become: True
  lxd_container:
    name: "{{ lxc_CT_NAME2 }}"
    state: started
    ignore_volatile_options: true
    source:
      type: image
      mode: pull
      server: "{{ lxc_image_source }}"
      protocol: simplestreams
      alias: "{{ lxc_container_distro }}"
    profiles: "{{ lxc_profiles }}"
    wait_for_ipv4_addresses: true
    timeout: 10
  when: lxc_lxd_host is defined
  register: container_Nginx

- name: List name of LXC network file in Nginx LXC path /etc/netplan/
  shell: lxc exec "{{ lxc_CT_NAME2 }}" ls /etc/netplan/
  register: file_of_Nginx

- debug:
    msg: "{{ file_of_Nginx.stdout }}"

- name: Copy new IP to container Nginx
  shell: |
    lxc file push /etc/ansible/roles/lxd_qs/files/192.168.100.121.yaml local:"{{ lxc_CT_NAME2 }}"/etc/netplan/"{{ file_of_Nginx.stdout }}"
    lxc exec "{{ lxc_CT_NAME2 }}" netplan apply

- name: Show us new IP of Nginx container
  shell: lxc exec "{{ lxc_CT_NAME2 }}" -- ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1
  register: ip_of_container_Nginx

- debug:
    msg: "{{ ip_of_container_Nginx.stdout }}"
